adding telegram integration
mholt/timeliner pull request #26
Opened 2019-03-26 21:49 UTC by hstolte

Hi, here is a draft for integrating the telegram data export into timeliner (issue #17).

There are a couple of things that would need to be sorted out before merging the pull request. 

1. The telegram archive contains a lot of files that potentially have the same name (e.g. "giphy.mp4" or "sticker.webp"). I tried to circumvent the issue of overwritten files by prepending a hash of the timestamp and conversation id to the filename, but still, I can see some errors during the import and some files seem to be missing. Do you have any ideas? Here is the error message:
``[ERROR] Processing item graph: processing collection: adding item from collection to storage: replacing data file with identical existing file: removing duplicate data file: remove timeliner_repo\data\2018\04\telegram\2505156913-video9.mp4: The process cannot access the file because it is being used by another process.``

2. The datetime strings in this data source do not have any timezone information. Therefore I would suggest to add a custom parameter for the default timezone. See ``line 61`` onwards in ``telegram.go``

2019-03-27 00:20 UTC, mholt commented
Awesome! Will take a look at it soon. This reminds me, I need to set up CI.

2019-03-30 04:55 UTC, mholt requested changes
Solid start! I just made a quick first pass over the change so far.

2019-03-30 04:55 UTC, mholt commented on datasources/telegram/models.go
> +	PhoneNumber string `json:"phone_number				"`
Extra spaces in struct tag

2019-03-30 04:55 UTC, mholt commented on datasources/telegram/models.go
> +//  ------------------------------- Telegram Message ---------------------------------------------------------
You could keep these all in one file if you want, but based on how you have this separated, I'd at least suggest just putting these sections/models in different files.

2019-03-30 04:55 UTC, mholt commented on datasources/telegram/models.go
> +// this type either returns the string or concatenates all strings and object's text attributes into a string
Shorter comment lines would be nice.

Also, follow godoc convention: "UnmarshalJSON ..."

2019-03-30 04:55 UTC, mholt commented on datasources/telegram/models.go
> +	// (e.g. redundant names like "giphy.mp4" or "sticker.webp" are actually different files with identical names...
Shorter comment lines again please :)

2019-03-30 04:55 UTC, mholt commented on datasources/telegram/telegram.go
> +	DataSourceID   = "telegram" // TODO: snake_cased unique name
Remove TODOs

2019-06-12 17:04 UTC, mholt commented
> but still, I can see some errors during the import and some files seem to be missing. Do you have any ideas?

Are you using Windows perchance?

> The datetime strings in this data source do not have any timezone information. Therefore I would suggest to add a custom parameter for the default timezone. 

We could either default to UTC or make the time zone configurable as a parameter, yes.

2019-06-12 17:52 UTC, hstolte commented
> Are you using Windows perchance?
Yes, I do. However, no other application is accessing or locking the files in parallel.

2019-06-20 23:03 UTC, mholt commented
I'm not sure. Please let us know if you find out! Would love to fix it.

2019-08-02 15:07 UTC, mholt commented
Closing due to inactivity. Feel free to continue working on this and then open it back up if you feel like it!

2019-08-02 15:07 UTC, closed without merging